name: karriba
description: "An intuitive commercial drone record-keeping system that keeps getting better"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.4.0+6

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.7
  sqflite: ^2.3.0
  path: ^1.9.1
  intl: ^0.20.2
  file_picker: ^9.1.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  drift: ^2.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
