name: karriba
description: "An intuitive commercial drone record-keeping system that keeps getting better"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.7
  sqflite: ^2.3.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
