name: Flutter Build APK

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '21.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk
      - run: pwd
      - run: ls build
      - run: ls build/app
      - run: ls build/app/outputs
      - run: ls build/app/outputs/flutter-apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
